// prevajanje datoteke *.proto na Arnes HPC:
//   - namestitev modulov
//      module load protobuf
//      module load binutils/2.39-GCCcore-12.2.0
//      go install google.golang.org/protobuf/cmd/protoc-gen-go@latest (samo ob prvi uporabi)
//      go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest (samo ob prvi uporabi)
//      export PATH="$PATH:$(go env GOPATH)/bin"
//   - prevajanje
//      srun protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative protobufStorage.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protobufStorage.proto

package protobufStorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          string                 `protobuf:"bytes,1,opt,name=Task,proto3" json:"Task,omitempty"`
	Completed     bool                   `protobuf:"varint,2,opt,name=Completed,proto3" json:"Completed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_protobufStorage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

type TodoStorage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodoStorage) Reset() {
	*x = TodoStorage{}
	mi := &file_protobufStorage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodoStorage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoStorage) ProtoMessage() {}

func (x *TodoStorage) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoStorage.ProtoReflect.Descriptor instead.
func (*TodoStorage) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{1}
}

func (x *TodoStorage) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

var File_protobufStorage_proto protoreflect.FileDescriptor

const file_protobufStorage_proto_rawDesc = "" +
	"\n" +
	"\x15protobufStorage.proto\x12\x0fprotobufStorage\x1a\x1bgoogle/protobuf/empty.proto\"8\n" +
	"\x04Todo\x12\x12\n" +
	"\x04Task\x18\x01 \x01(\tR\x04Task\x12\x1c\n" +
	"\tCompleted\x18\x02 \x01(\bR\tCompleted\":\n" +
	"\vTodoStorage\x12+\n" +
	"\x05todos\x18\x01 \x03(\v2\x15.protobufStorage.TodoR\x05todos2\xaa\x02\n" +
	"\x04CRUD\x127\n" +
	"\x06Create\x12\x15.protobufStorage.Todo\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x04Read\x12\x15.protobufStorage.Todo\x1a\x1c.protobufStorage.TodoStorage\x127\n" +
	"\x06Update\x12\x15.protobufStorage.Todo\x1a\x16.google.protobuf.Empty\x127\n" +
	"\x06Delete\x12\x15.protobufStorage.Todo\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\aReadAll\x12\x16.google.protobuf.Empty\x1a\x15.protobufStorage.Todo0\x01B\x12Z\x10/protobufStorageb\x06proto3"

var (
	file_protobufStorage_proto_rawDescOnce sync.Once
	file_protobufStorage_proto_rawDescData []byte
)

func file_protobufStorage_proto_rawDescGZIP() []byte {
	file_protobufStorage_proto_rawDescOnce.Do(func() {
		file_protobufStorage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufStorage_proto_rawDesc), len(file_protobufStorage_proto_rawDesc)))
	})
	return file_protobufStorage_proto_rawDescData
}

var file_protobufStorage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobufStorage_proto_goTypes = []any{
	(*Todo)(nil),          // 0: protobufStorage.Todo
	(*TodoStorage)(nil),   // 1: protobufStorage.TodoStorage
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_protobufStorage_proto_depIdxs = []int32{
	0, // 0: protobufStorage.TodoStorage.todos:type_name -> protobufStorage.Todo
	0, // 1: protobufStorage.CRUD.Create:input_type -> protobufStorage.Todo
	0, // 2: protobufStorage.CRUD.Read:input_type -> protobufStorage.Todo
	0, // 3: protobufStorage.CRUD.Update:input_type -> protobufStorage.Todo
	0, // 4: protobufStorage.CRUD.Delete:input_type -> protobufStorage.Todo
	2, // 5: protobufStorage.CRUD.ReadAll:input_type -> google.protobuf.Empty
	2, // 6: protobufStorage.CRUD.Create:output_type -> google.protobuf.Empty
	1, // 7: protobufStorage.CRUD.Read:output_type -> protobufStorage.TodoStorage
	2, // 8: protobufStorage.CRUD.Update:output_type -> google.protobuf.Empty
	2, // 9: protobufStorage.CRUD.Delete:output_type -> google.protobuf.Empty
	0, // 10: protobufStorage.CRUD.ReadAll:output_type -> protobufStorage.Todo
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobufStorage_proto_init() }
func file_protobufStorage_proto_init() {
	if File_protobufStorage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufStorage_proto_rawDesc), len(file_protobufStorage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobufStorage_proto_goTypes,
		DependencyIndexes: file_protobufStorage_proto_depIdxs,
		MessageInfos:      file_protobufStorage_proto_msgTypes,
	}.Build()
	File_protobufStorage_proto = out.File
	file_protobufStorage_proto_goTypes = nil
	file_protobufStorage_proto_depIdxs = nil
}
